average_ratio: 2
client: 3
contains_country_ar: 2
contains_country_es: 2
creditdispatcher: 2
credits_unwinder: 2
creditsplitter: 2
filter_by_year_after_2000: 2
filter_by_year_before_2010: 2
gateway: 2
moviecreditjoiner: 2
moviecreditsharder: 2
movieratingjoiner: 2
movieratingsharder: 2
movies_selector: 2
onlyoneprodcountry: 2
ratingdispatcher: 2
ratings_selector: 2
ratingsplitter: 2
rentability: 2
resultq1: 2
resultq2: 2
resultq3: 2
resultq4: 2
resultq5: 2
sentiment: 2
top_appearances: 2
top_ranking: 2
top_rating: 2
yearselector: 2
health: 5